// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test0001.Models;

#nullable disable

namespace Test0001.Migrations
{
    [DbContext(typeof(CodeFirstDbContext))]
    [Migration("20251024154851_AddOperatorMigration")]
    partial class AddOperatorMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookmarks", b =>
                {
                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("MoviesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("DirectorsMovies", b =>
                {
                    b.Property<int>("DirectorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("DirectorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("DirectorsMovies");

                    b.HasData(
                        new
                        {
                            DirectorsId = 1,
                            MoviesId = 6
                        },
                        new
                        {
                            DirectorsId = 2,
                            MoviesId = 6
                        },
                        new
                        {
                            DirectorsId = 1,
                            MoviesId = 7
                        },
                        new
                        {
                            DirectorsId = 2,
                            MoviesId = 7
                        },
                        new
                        {
                            DirectorsId = 3,
                            MoviesId = 1
                        },
                        new
                        {
                            DirectorsId = 5,
                            MoviesId = 2
                        },
                        new
                        {
                            DirectorsId = 6,
                            MoviesId = 3
                        },
                        new
                        {
                            DirectorsId = 4,
                            MoviesId = 4
                        },
                        new
                        {
                            DirectorsId = 7,
                            MoviesId = 5
                        },
                        new
                        {
                            DirectorsId = 8,
                            MoviesId = 5
                        });
                });

            modelBuilder.Entity("Test0001.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("smalldatetime");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(6821),
                            Name = "Fantasy",
                            OperatorId = 1,
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(6826)
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(7327),
                            Name = "Thriller",
                            OperatorId = 1,
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(7327)
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(7329),
                            Name = "Comedy",
                            OperatorId = 1,
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(7329)
                        });
                });

            modelBuilder.Entity("Test0001.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Test0001.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("smalldatetime");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8751),
                            Name = "Phil",
                            OperatorId = 1,
                            Surname = "Lord",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8752)
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9253),
                            Name = "Chris",
                            OperatorId = 1,
                            Surname = "Miller",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9253)
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9255),
                            Name = "Alfonso",
                            OperatorId = 1,
                            Surname = "Cuaròn",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9255)
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9256),
                            Name = "Peter",
                            OperatorId = 1,
                            Surname = "Jackson",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9256)
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9257),
                            Name = "Brad",
                            OperatorId = 1,
                            Surname = "Anderson",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9258)
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9260),
                            Name = "Massimo",
                            OperatorId = 1,
                            Surname = "Venier",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9260)
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9261),
                            Name = "Chris",
                            OperatorId = 1,
                            Surname = "Wedge",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9261)
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9262),
                            Name = "Carlos",
                            OperatorId = 1,
                            Surname = "Saldanha",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(9263)
                        });
                });

            modelBuilder.Entity("Test0001.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("smalldatetime");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(7896),
                            OperatorId = 1,
                            ReleaseDate = new DateOnly(1, 1, 1),
                            Title = "Harry Potter and The Prisoner of Azkaban",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(7896)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8332),
                            OperatorId = 1,
                            ReleaseDate = new DateOnly(1, 1, 1),
                            Title = "Fractured",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8332)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8334),
                            OperatorId = 1,
                            ReleaseDate = new DateOnly(1, 1, 1),
                            Title = "Tre uomini e una gamba",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8334)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8335),
                            OperatorId = 1,
                            ReleaseDate = new DateOnly(1, 1, 1),
                            Title = "The Fellowship of the Ring",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8335)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8336),
                            OperatorId = 1,
                            ReleaseDate = new DateOnly(1, 1, 1),
                            Title = "Ice age",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8336)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8337),
                            OperatorId = 1,
                            ReleaseDate = new DateOnly(1, 1, 1),
                            Title = "Cloudy with a chance of meatballs",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8338)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8341),
                            OperatorId = 1,
                            ReleaseDate = new DateOnly(1, 1, 1),
                            Title = "The LEGO Movie",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(8342)
                        });
                });

            modelBuilder.Entity("Test0001.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OperatorName = "admin"
                        });
                });

            modelBuilder.Entity("Test0001.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(3860),
                            Email = "marta@example.com",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(3865),
                            Username = "marta"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(4630),
                            Email = "claudio@example.com",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(4630),
                            Username = "spazzabilly"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(4632),
                            Email = "abriged@example.com",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(4632),
                            Username = "GiulioAbridged"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(4633),
                            Email = "jack@example.com",
                            UpdateDate = new DateTime(2025, 10, 24, 15, 48, 51, 123, DateTimeKind.Utc).AddTicks(4633),
                            Username = "jackomino"
                        });
                });

            modelBuilder.Entity("Bookmarks", b =>
                {
                    b.HasOne("Test0001.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test0001.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectorsMovies", b =>
                {
                    b.HasOne("Test0001.Models.Director", null)
                        .WithMany()
                        .HasForeignKey("DirectorsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Test0001.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Test0001.Models.Category", b =>
                {
                    b.HasOne("Test0001.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Test0001.Models.Comment", b =>
                {
                    b.HasOne("Test0001.Models.Movie", "Movie")
                        .WithMany("Comments")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test0001.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Test0001.Models.Director", b =>
                {
                    b.HasOne("Test0001.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Test0001.Models.Movie", b =>
                {
                    b.HasOne("Test0001.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test0001.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Test0001.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Test0001.Models.Movie", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Test0001.Models.User", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
